Feature desktop version
NatanimA/Microverse-Portfolio-Project pull request #4
Opened 2022-08-23 18:14 UTC by NatanimA

-->Inserted Desktop Background for each sections
--->Used media queries to fix the pixel sizing's to fit on the desktop
--->Inserted Hover effects on the navigations and logo
---->Correct navigation for each sections
---->clean and precise version for Desktop 😉

2022-08-23 18:44 UTC, sumairq requested changes
### Hi Team, 

<img src="https://media4.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 18:44 UTC, sumairq commented on css/style.css
> +  }
- [ ] Same here, kindly try to match the background of contact form to the Figma template.  Cheers 👍

Figma Design             |  Your Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/60618877/186236388-81d58034-6112-40cf-91b4-2bfa95cf1654.png)  |  ![image](https://user-images.githubusercontent.com/60618877/186236296-e2578e82-07b2-4c7f-adc7-aee93a8f8e15.png)

2022-08-23 18:44 UTC, sumairq commented on css/style.css
> +  }
- [ ] The "languages" section should be horizontal at desktop width, instead it remains the vertical, same as the mobile width.
 Kindly fix it so that your design perfectly matches the Figma design. Cheers 👍 

Figma Design             |  Your Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/60618877/186236655-8fa85534-5dfc-4a80-a936-b873ca8107a2.png)  |  ![image](https://user-images.githubusercontent.com/60618877/186236858-665f74f6-7a01-4cc8-a8f2-9b883458c338.png)

2022-08-23 18:44 UTC, sumairq commented on css/style.css
> +  }
- [ ] Let's ensure that background image appears the same as the Figma template.  Cheers 👍 

Figma Design             |  Your Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/60618877/186235527-db35722b-b557-47ef-85d2-95b08205aa77.png)  | ![image](https://user-images.githubusercontent.com/60618877/186237204-7c5cf580-7878-421e-ad82-a38d26f2c1a3.png)

2022-08-23 18:52 UTC, NatanimA commented on css/style.css
> +  }
Hello I faced this problem earlier but i couldn't manage to make it the same background as the figma template, can you suggest anything if i can rotate the background or something please? @sumairq  🥺 🙏🏼

2022-08-24 09:52 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @NatanimA 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job implementing the requirements by the previous reviewer ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

- [OPTIONAL] I suggest updating your README file by removing the unnecessary section, and I suggest adding the `MIT.md` file to your project 👌, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 10:00 UTC, merged